; generated by PrusaSlicer 2.9.1 on 2025-03-24 at 04:06:19 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object cube.stl id:0 copy 0
; stop printing object cube.stl id:0 copy 0

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S60 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S60 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S215 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M73 P7 R0
M109 S215 ; wait for extruder temp

; intro line
G1 X170 F1000
M73 P8 R0
G1 Z0.2 F720
M73 P9 R0
G1 X110 E8 F900
G1 X40 E10 F700
M73 P16 R0
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode LA 1.5
; ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 E-3.2 F4200
M73 P26 R0
G1 Z.4 F720
G1 X86.797 Y86.031 F9000
M73 P27 R0
G1 Z.2 F720
M73 P28 R0
G1 E3.2 F2400
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X89 Y85.303 E.07275
G1 X91 Y85.303 E.06271
G1 X92.662 Y85.698 E.05356
G1 X93.969 Y86.797 E.05354
M73 P29 R0
G1 X94.697 Y89 E.07275
G1 X94.697 Y91 E.06271
G1 X94.302 Y92.662 E.05356
G1 X93.203 Y93.969 E.05354
M73 P30 R0
G1 X91 Y94.697 E.07275
G1 X89 Y94.697 E.06271
G1 X87.338 Y94.302 E.05356
G1 X86.031 Y93.203 E.05354
G1 X85.303 Y91 E.07275
M73 P31 R0
G1 X85.303 Y89 E.06271
G1 X85.698 Y87.338 E.05356
G1 X86.759 Y86.077 E.05167
M204 P1000
G1 X87.058 Y86.35 F9000
M73 P32 R0
M204 P800
G1 F900
G1 X87.163 Y86.235 E.00488
G1 X89 Y85.68 E.06017
G1 X91 Y85.68 E.06271
G1 X92.569 Y86.074 E.05072
G1 X93.765 Y87.163 E.05072
G1 X94.32 Y89 E.06017
G1 X94.32 Y91 E.06271
M73 P33 R0
G1 X93.926 Y92.569 E.05072
G1 X92.837 Y93.765 E.05072
G1 X91 Y94.32 E.06017
G1 X89 Y94.32 E.06271
G1 X87.431 Y93.926 E.05072
M73 P34 R0
G1 X86.235 Y92.837 E.05072
G1 X85.68 Y91 E.06017
G1 X85.68 Y89 E.06271
G1 X86.074 Y87.431 E.05072
M73 P35 R0
G1 X87.018 Y86.394 E.04397
M204 P1000
G1 X87.302 Y86.677 F9000
M204 P800
G1 F900
G1 X87.525 Y86.454 E.00989
G1 X89 Y86.057 E.04789
G1 X91 Y86.057 E.06271
G1 X92.47 Y86.451 E.04772
G1 X93.546 Y87.525 E.04767
M73 P36 R0
G1 X93.943 Y89 E.04789
G1 X93.943 Y91 E.06271
G1 X93.549 Y92.47 E.04772
G1 X92.475 Y93.546 E.04767
G1 X91 Y93.943 E.04789
G1 X89 Y93.943 E.06271
M73 P37 R0
G1 X87.53 Y93.549 E.04772
G1 X86.454 Y92.475 E.04767
G1 X86.057 Y91 E.04789
G1 X86.057 Y89 E.06271
G1 X86.451 Y87.53 E.04772
M73 P38 R0
G1 X87.259 Y86.72 E.03587
M204 P1000
G1 X87.522 Y87.013 F9000
M204 P800
G1 F900
G1 X87.883 Y86.69 E.01519
G1 X89 Y86.434 E.03593
G1 X91 Y86.434 E.06271
G1 X92.363 Y86.827 E.04448
G1 X93.31 Y87.883 E.04447
M73 P39 R0
G1 X93.566 Y89 E.03593
G1 X93.566 Y91 E.06271
G1 X93.173 Y92.363 E.04448
G1 X92.117 Y93.31 E.04447
G1 X91 Y93.566 E.03593
G1 X89 Y93.566 E.06271
M73 P40 R0
G1 X87.637 Y93.173 E.04448
G1 X86.69 Y92.117 E.04447
G1 X86.434 Y91 E.03593
G1 X86.434 Y89 E.06271
G1 X86.827 Y87.637 E.04448
G1 X87.478 Y87.053 E.02742
M73 P41 R0
M204 P1000
G1 X87.712 Y87.356 F9000
M204 P800
G1 F900
G1 X88.235 Y86.949 E.02078
G1 X89 Y86.811 E.02437
G1 X91 Y86.811 E.06271
G1 X92.248 Y87.202 E.04101
G1 X93.051 Y88.235 E.04102
G1 X93.189 Y89 E.02437
G1 X93.189 Y91 E.06271
M73 P42 R0
G1 X92.798 Y92.248 E.04101
G1 X91.765 Y93.051 E.04102
G1 X91 Y93.189 E.02437
G1 X89 Y93.189 E.06271
G1 X87.752 Y92.798 E.04101
G1 X86.949 Y91.765 E.04102
M73 P43 R0
G1 X86.811 Y91 E.02437
G1 X86.811 Y89 E.06271
G1 X87.202 Y87.752 E.04101
G1 X87.665 Y87.392 E.01839
M204 P1000
G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X87.712 Y87.356 E-.03281
G1 X88.235 Y86.949 E-.36725
G1 X89 Y86.811 E-.43078
G1 X89.233 Y86.811 E-.12916
;WIPE_END
G1 Z.4 F720
; printing object cube.stl id:0 copy 0
G1 X89.587 Y89.587 F9000
M73 P44 R0
G1 Z.2 F720
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F900
G1 X90.413 Y89.587 E.0259
G1 X90.413 Y90 E.01295
G1 X90.413 Y90.413 E.01295
G1 X89.587 Y90.413 E.0259
G1 X89.587 Y89.647 E.02402
M204 P1000
G1 X89.21 Y89.21 F9000
M204 P800
;TYPE:External perimeter
G1 F900
G1 X90.79 Y89.21 E.04954
G1 X90.79 Y90 E.02477
M73 P45 R0
G1 X90.79 Y90.79 E.02477
G1 X89.21 Y90.79 E.04954
G1 X89.21 Y89.27 E.04766
M204 P1000
M106 S84.15
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.21 Y89.21 E-.03325
G1 X90.79 Y89.21 E-.87558
G1 X90.79 Y89.302 E-.05117
;WIPE_END
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.4
; stop printing object cube.stl id:0 copy 0
G1 Z.6
G1 X88.008 Y85.631 F9000
G1 Z.4 F720
M73 P46 R0
G1 E3.2 F2400
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X89 Y85.303 E.03276
G1 X91 Y85.303 E.06271
G1 X92.662 Y85.698 E.05356
G1 X93.969 Y86.797 E.05354
G1 X94.697 Y89 E.07275
M73 P47 R0
G1 X94.697 Y91 E.06271
G1 X94.302 Y92.662 E.05356
G1 X93.203 Y93.969 E.05354
G1 X91 Y94.697 E.07275
G1 X89 Y94.697 E.06271
M73 P48 R0
G1 X87.338 Y94.302 E.05356
G1 X86.031 Y93.203 E.05354
G1 X85.303 Y91 E.07275
G1 X85.303 Y89 E.06271
M73 P49 R0
G1 X85.698 Y87.338 E.05356
G1 X86.797 Y86.031 E.05354
G1 X87.951 Y85.65 E.0381
G1 X88.047 Y85.968 F9000
G1 F900
G1 X89 Y85.68 E.03122
G1 X91 Y85.68 E.06271
G1 X92.569 Y86.074 E.05072
M73 P50 R0
G1 X93.765 Y87.163 E.05072
G1 X94.32 Y89 E.06017
G1 X94.32 Y91 E.06271
G1 X93.926 Y92.569 E.05072
M73 P51 R0
G1 X92.837 Y93.765 E.05072
G1 X91 Y94.32 E.06017
G1 X89 Y94.32 E.06271
G1 X87.431 Y93.926 E.05072
G1 X86.235 Y92.837 E.05072
M73 P52 R0
G1 X85.68 Y91 E.06017
G1 X85.68 Y89 E.06271
G1 X86.074 Y87.431 E.05072
G1 X87.163 Y86.235 E.05072
G1 X87.989 Y85.985 E.02706
M73 P53 R0
G1 X88.075 Y86.306 F9000
G1 F900
G1 X89 Y86.057 E.03004
G1 X91 Y86.057 E.06271
G1 X92.47 Y86.451 E.04772
G1 X93.546 Y87.525 E.04767
G1 X93.943 Y89 E.04789
G1 X93.943 Y91 E.06271
M73 P54 R0
G1 X93.549 Y92.47 E.04772
G1 X92.475 Y93.546 E.04767
G1 X91 Y93.943 E.04789
G1 X89 Y93.943 E.06271
G1 X87.53 Y93.549 E.04772
M73 P55 R0
G1 X86.454 Y92.475 E.04767
G1 X86.057 Y91 E.04789
G1 X86.057 Y89 E.06271
G1 X86.451 Y87.53 E.04772
G1 X87.525 Y86.454 E.04767
G1 X88.017 Y86.321 E.01598
M73 P56 R0
G1 X88.091 Y86.643 F9000
G1 F900
G1 X89 Y86.434 E.02924
G1 X91 Y86.434 E.06271
G1 X92.363 Y86.827 E.04448
G1 X93.31 Y87.883 E.04447
G1 X93.566 Y89 E.03593
G1 X93.566 Y91 E.06271
M73 P57 R0
G1 X93.173 Y92.363 E.04448
G1 X92.117 Y93.31 E.04447
G1 X91 Y93.566 E.03593
G1 X89 Y93.566 E.06271
G1 X87.637 Y93.173 E.04448
G1 X86.69 Y92.117 E.04447
M73 P58 R0
G1 X86.434 Y91 E.03593
G1 X86.434 Y89 E.06271
G1 X86.827 Y87.637 E.04448
G1 X87.883 Y86.69 E.04447
G1 X88.032 Y86.656 E.00479
G1 X88.235 Y86.949 F9000
G1 F900
M73 P59 R0
G1 X89 Y86.811 E.02437
G1 X91 Y86.811 E.06271
G1 X92.248 Y87.202 E.04101
G1 X93.051 Y88.235 E.04102
G1 X93.189 Y89 E.02437
G1 X93.189 Y91 E.06271
G1 X92.798 Y92.248 E.04101
G1 X91.765 Y93.051 E.04102
M73 P60 R0
G1 X91 Y93.189 E.02437
G1 X89 Y93.189 E.06271
G1 X87.752 Y92.798 E.04101
G1 X86.949 Y91.765 E.04102
G1 X86.811 Y91 E.02437
G1 X86.811 Y89 E.06271
G1 X87.202 Y87.752 E.04101
M73 P61 R0
G1 X88.188 Y86.986 E.03915
G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X88.235 Y86.949 E-.03315
G1 X89 Y86.811 E-.43078
G1 X89.895 Y86.811 E-.49607
;WIPE_END
G1 Z.6 F720
; printing object cube.stl id:0 copy 0
G1 X89.714 Y89.714 F9000
G1 Z.4 F720
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
M73 P62 R0
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M73 P63 R0
M204 P1000
M106 S170.85
;LAYER_CHANGE
;Z:0.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z.6 F720
;AFTER_LAYER_CHANGE
;0.6
; stop printing object cube.stl id:0 copy 0
G1 Z.8
G1 X88.017 Y85.628 F9000
G1 Z.6 F720
G1 E3.2 F2400
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F900
G1 X89 Y85.303 E.03246
G1 X91 Y85.303 E.06271
M73 P64 R0
G1 X92.662 Y85.698 E.05356
G1 X93.969 Y86.797 E.05354
G1 X94.697 Y89 E.07275
G1 X94.697 Y91 E.06271
G1 X94.302 Y92.662 E.05356
M73 P65 R0
G1 X93.203 Y93.969 E.05354
G1 X91 Y94.697 E.07275
G1 X89 Y94.697 E.06271
G1 X87.338 Y94.302 E.05356
M73 P66 R0
G1 X86.031 Y93.203 E.05354
G1 X85.303 Y91 E.07275
G1 X85.303 Y89 E.06271
G1 X85.698 Y87.338 E.05356
G1 X86.797 Y86.031 E.05354
M73 P67 R0
G1 X87.96 Y85.647 E.0384
G1 X88.056 Y85.965 F9000
G1 F900
G1 X89 Y85.68 E.03092
G1 X91 Y85.68 E.06271
G1 X92.569 Y86.074 E.05072
G1 X93.765 Y87.163 E.05072
M73 P68 R0
G1 X94.32 Y89 E.06017
G1 X94.32 Y91 E.06271
G1 X93.926 Y92.569 E.05072
G1 X92.837 Y93.765 E.05072
G1 X91 Y94.32 E.06017
M73 P69 R0
G1 X89 Y94.32 E.06271
G1 X87.431 Y93.926 E.05072
G1 X86.235 Y92.837 E.05072
G1 X85.68 Y91 E.06017
G1 X85.68 Y89 E.06271
M73 P70 R0
G1 X86.074 Y87.431 E.05072
G1 X87.163 Y86.235 E.05072
G1 X87.998 Y85.983 E.02735
G1 X88.084 Y86.303 F9000
G1 F900
G1 X89 Y86.057 E.02974
G1 X91 Y86.057 E.06271
G1 X92.47 Y86.451 E.04772
M73 P71 R0
G1 X93.546 Y87.525 E.04767
G1 X93.943 Y89 E.04789
G1 X93.943 Y91 E.06271
G1 X93.549 Y92.47 E.04772
G1 X92.475 Y93.546 E.04767
M73 P72 R0
G1 X91 Y93.943 E.04789
G1 X89 Y93.943 E.06271
G1 X87.53 Y93.549 E.04772
G1 X86.454 Y92.475 E.04767
G1 X86.057 Y91 E.04789
M73 P73 R0
G1 X86.057 Y89 E.06271
G1 X86.451 Y87.53 E.04772
G1 X87.525 Y86.454 E.04767
G1 X88.027 Y86.319 E.0163
G1 X88.1 Y86.64 F9000
G1 F900
G1 X89 Y86.434 E.02895
G1 X91 Y86.434 E.06271
G1 X92.363 Y86.827 E.04448
M73 P74 R0
G1 X93.31 Y87.883 E.04447
G1 X93.566 Y89 E.03593
G1 X93.566 Y91 E.06271
G1 X93.173 Y92.363 E.04448
G1 X92.117 Y93.31 E.04447
M73 P75 R0
G1 X91 Y93.566 E.03593
G1 X89 Y93.566 E.06271
G1 X87.637 Y93.173 E.04448
G1 X86.69 Y92.117 E.04447
G1 X86.434 Y91 E.03593
G1 X86.434 Y89 E.06271
M73 P76 R0
G1 X86.827 Y87.637 E.04448
G1 X87.883 Y86.69 E.04447
G1 X88.042 Y86.654 E.00511
G1 X88.235 Y86.949 F9000
G1 F900
G1 X89 Y86.811 E.02437
G1 X91 Y86.811 E.06271
G1 X92.248 Y87.202 E.04101
G1 X93.051 Y88.235 E.04102
M73 P77 R0
G1 X93.189 Y89 E.02437
G1 X93.189 Y91 E.06271
G1 X92.798 Y92.248 E.04101
G1 X91.765 Y93.051 E.04102
G1 X91 Y93.189 E.02437
G1 X89 Y93.189 E.06271
G1 X87.752 Y92.798 E.04101
M73 P78 R0
G1 X86.949 Y91.765 E.04102
G1 X86.811 Y91 E.02437
G1 X86.811 Y89 E.06271
G1 X87.202 Y87.752 E.04101
G1 X88.188 Y86.986 E.03915
G1 E-2.24 F4200
M73 P79 R0
;WIPE_START
G1 F7200
G1 X88.235 Y86.949 E-.03315
G1 X89 Y86.811 E-.43078
G1 X89.895 Y86.811 E-.49607
;WIPE_END
G1 Z.8 F720
; printing object cube.stl id:0 copy 0
G1 X89.714 Y89.714 F9000
G1 Z.6 F720
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M73 P80 R0
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
M106 S255
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
M73 P81 R0
;WIPE_END
G1 Z.8 F720
;AFTER_LAYER_CHANGE
;0.8
G1 Z.8
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
M73 P82 R0
G1 X89.225 Y89.285 E.05043
M204 P1000
;LAYER_CHANGE
;Z:1
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z1 F720
;AFTER_LAYER_CHANGE
;1
G1 Z1
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
M73 P83 R0
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
;LAYER_CHANGE
;Z:1.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2


G1 E-2.24 F4200
M73 P84 R0
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z1.2 F720
;AFTER_LAYER_CHANGE
;1.2
G1 Z1.2
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
M73 P85 R0
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z1.4 F720
;AFTER_LAYER_CHANGE
;1.4
G1 Z1.4
M73 P86 R0
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M73 P87 R0
M204 P1000
;LAYER_CHANGE
;Z:1.6
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.6


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z1.6 F720
;AFTER_LAYER_CHANGE
;1.6
G1 Z1.6
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
M73 P88 R0
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.8


G1 E-2.24 F4200
;WIPE_START
G1 F7200
M73 P89 R0
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z1.8 F720
;AFTER_LAYER_CHANGE
;1.8
G1 Z1.8
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
M73 P90 R0
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
;LAYER_CHANGE
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
G1 Z2 F720
;AFTER_LAYER_CHANGE
;2
G1 Z2
G1 X89.714 Y89.714 F9000
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.614381
G1 F900
M73 P91 R0
G1 X90.286 Y89.714 E.02718
G1 X90.286 Y90 E.01359
G1 X90.286 Y90.286 E.01359
G1 X89.714 Y90.286 E.02718
G1 X89.714 Y89.774 E.02433
M204 P1000
G1 X89.225 Y89.225 F9000
M204 P800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F900
G1 X90.775 Y89.225 E.05247
G1 X90.775 Y90 E.02623
G1 X90.775 Y90.775 E.02623
G1 X89.225 Y90.775 E.05247
G1 X89.225 Y89.285 E.05043
M204 P1000
; stop printing object cube.stl id:0 copy 0
G1 E-2.24 F4200
M73 P92 R0
;WIPE_START
G1 F7200;_WIPE
G1 X89.225 Y89.225 E-.03325
G1 X90.775 Y89.225 E-.85896
G1 X90.775 Y89.347 E-.06779
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z4 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z32 F720 ; Move print head further up
M73 P95 R0
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; objects_info = {"objects":[{"name":"cube.stl id:0 copy 0","polygon":[[91.000,91.000],[89.000,91.000],[89.000,89.000],[91.000,89.000]]}]}
; filament used [mm] = 33.45
; filament used [cm3] = 0.08
; filament used [g] = 0.10
; filament cost = 0.00
; total filament used [g] = 0.10
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 58s
; estimated first layer printing time (normal mode) = 26s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30.24
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = 15%
; filament_settings_id = "Prusament PLA"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 201
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; filament_wipe = nil
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_infill_speed = 0
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; idle_temperature = nil
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 0.20mm QUALITY @MINI
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 16x16/PNG, 220x124/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
